const dataConfigSchool = {
  name: "SMK NEGERI 1 LUMBAN JULU",
  historySchool:
    "SMK Negeri 1 Lumban Julu adalah institusi pendidikan kejuruan yang berfokus pada pengembangan keterampilan siswa di bidang teknologi, bisnis, dan layanan masyarakat. Kami berdedikasi untuk mencetak lulusan yang siap bersaing di dunia kerja maupun melanjutkan pendidikan ke jenjang yang lebih tinggi.",
  about:
    "SMK Negeri 1 Lumban Julu adalah institusi pendidikan kejuruan yang berfokus pada pengembangan keterampilan siswa di bidang teknologi, bisnis, dan layanan masyarakat. Kami berdedikasi untuk mencetak lulusan yang siap bersaing di dunia kerja maupun melanjutkan pendidikan ke jenjang yang lebih tinggi.",
  vision:
    "Menjadi sekolah kejuruan unggulan yang menghasilkan lulusan berkualitas, berkarakter, dan berkompeten di bidangnya untuk bersaing di era global.",
  mission:
    "1. Menyediakan pendidikan kejuruan yang berbasis teknologi dan kewirausahaan.\n2. Meningkatkan kompetensi siswa melalui pelatihan praktik kerja industri.\n3. Membentuk karakter siswa yang jujur, disiplin, dan bertanggung jawab.\n4. Mengembangkan kurikulum yang relevan dengan kebutuhan dunia kerja.\n5. Menjalin kemitraan dengan dunia usaha dan industri.",
  address: "Jalan Lintas Sumatera, Aeknatolu Jaya, Kecamatan Lumban Julu",
  telp: "+62 822-8302-0850",
  email: "info@smkn1lumbanjulu.sch.id",
  maps: '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15942.833059396076!2d99.0161061!3d2.6008913!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3031f01ad5a61e53%3A0xa1341928e9376e81!2sSMK%20Negeri%201%20Lumbanjulu!5e0!3m2!1sid!2sid!4v1731691727941!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  npsn: "12345678",
  fb: "https://facebook.com/smkn1lumbanjulu",
  ig: "https://instagram.com/smkn1lumbanjulu",
  tiktok: "https://tiktok.com/@smkn1lumbanjulu",
};

const customStudents = [
  {
    name: "Dhea Romantika",
    nis: "223344",
    nisn: "102938",
    majorCode: "TKJ",
    birthPlace: "Medan, 24 Februari 2003",
    address: "Jl. Mawar No.1",
    phone: "081234567890",
    email: "dhea.romantika@example.com",
    gender: "P",
  },
  {
    name: "Rizky Fadillah",
    nis: "112233",
    nisn: "203948",
    majorCode: "MM",
    birthPlace: "Jakarta, 17 Desember 2002",
    address: "Jl. Melati No.2",
    phone: "081234567891",
    email: "rizky.fadillah@example.com",
    gender: "L",
  },
  {
    name: "Muhammad Syahputra",
    nis: "334455",
    nisn: "304958",
    majorCode: "RPL",
    birthPlace: "Bandung, 22 April 2003",
    address: "Jl. Kenanga No.3",
    phone: "081234567892",
    email: "muhammad.syahputra@example.com",
    gender: "L",
  },
];

const dataMajor = [
  {
    name: "Teknik Komputer dan Jaringan",
    majorCode: "TKJ",
    description:
      "Jurusan yang berfokus pada teknologi komputer, jaringan, dan sistem keamanan data. Siswa akan mempelajari perakitan komputer, instalasi sistem operasi, administrasi server, serta konfigurasi jaringan lokal (LAN) dan internet.",
  },
  {
    name: "Multimedia ",
    majorCode: "MM",
    description:
      "Jurusan yang mengajarkan keterampilan dalam desain grafis, animasi, videografi, dan pengembangan media digital. Siswa akan mempelajari software desain, editing video, pembuatan konten kreatif, serta produksi media interaktif.",
  },
  {
    name: "Rekayasa Perangkat Lunak",
    majorCode: "RPL",
    description:
      "Jurusan yang berfokus pada pengembangan perangkat lunak, termasuk pemrograman, analisis sistem, dan manajemen basis data. Siswa akan belajar membuat aplikasi berbasis web, mobile, dan desktop menggunakan berbagai bahasa pemrograman.",
  },
  {
    name: "Teknik Instalasi Tenaga Listrik",
    majorCode: "TITL",
    description:
      "Jurusan yang mengajarkan tentang instalasi, perawatan, dan perbaikan sistem kelistrikan. Siswa akan mempelajari sistem tenaga listrik, instalasi rumah dan industri, serta perancangan dan perawatan jaringan listrik.",
  },
];

const dataDeveloper = {
  name: "developer",
  birthPlace: "21 Juni 1961",
  address: "Solo",
  phone: "08536746398",
  email: "developer@gmail.com",
  gender: "L",
  mapel: [],
  nip: "P001",
  type: "PH",
  position: "",
  startDate: new Date("2024-08-07"),
  role: "STAFF",
};

const dataStaff = [
    {
      name: "Drs Mutiha Hutajulu, M. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "mutiha.hutajulu@example.com",
      gender: "L",
      mapel: [],
      nip: "196603021990031008",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Arlen Manurung, S. Pd, M. Si",
      birthPlace: "",
      address: "",
      phone: "",
      email: "arlen.manurung@example.com",
      gender: "L",
      mapel: [],
      nip: "196410211988031001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Roslin Manurung, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "roslin.manurung@example.com",
      gender: "L",
      mapel: [],
      nip: "196502071988032004",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Dra. Uli M Tambunan",
      birthPlace: "",
      address: "",
      phone: "",
      email: "uli.tambunan@example.com",
      gender: "P",
      mapel: [],
      nip: "196711162005022001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Novelina Simanjuntak, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "novelina.simanjuntak@example.com",
      gender: "P",
      mapel: [],
      nip: "198311182008042001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Natalina Simaremare, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "natalina.simaremare@example.com",
      gender: "P",
      mapel: [],
      nip: "198112252009032005",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Santoso Sinaga, S. Th",
      birthPlace: "",
      address: "",
      phone: "",
      email: "santoso.sinaga@example.com",
      gender: "L",
      mapel: [],
      nip: "198206142009031001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Rosi Arta Sirait, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "rosi.sirait@example.com",
      gender: "P",
      mapel: [],
      nip: "198312202009032002",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Julian Situmorang, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "julian.situmorang@example.com",
      gender: "L",
      mapel: [],
      nip: "198407142009031003",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Frans R Situmeang, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "frans.situmeang@example.com",
      gender: "L",
      mapel: [],
      nip: "198002162009031002",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Pirman E Sinaga, S. Kom",
      birthPlace: "",
      address: "",
      phone: "",
      email: "pirman.sinaga@example.com",
      gender: "L",
      mapel: [],
      nip: "198301042010011016",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Roma Sitorus, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "roma.sitorus@example.com",
      gender: "P",
      mapel: [],
      nip: "198209062009032002",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "April Sirait, S. Kom",
      birthPlace: "",
      address: "",
      phone: "",
      email: "april.sirait@example.com",
      gender: "L",
      mapel: [],
      nip: "198204122010011034",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Naek Sirait, S. Si",
      birthPlace: "",
      address: "",
      phone: "",
      email: "naek.sirait@example.com",
      gender: "L",
      mapel: [],
      nip: "198103292011041001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Vivi Septianita Hutabarat, S. Kom",
      birthPlace: "",
      address: "",
      phone: "",
      email: "vivi.hutabarat@example.com",
      gender: "P",
      mapel: [],
      nip: "198609302015052001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Lenny R Butarbutar, S. Pd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "lenny.butarbutar@example.com",
      gender: "P",
      mapel: [],
      nip: "197605032014082001",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    },
    {
      name: "Chandra K Sinaga, Amd",
      birthPlace: "",
      address: "",
      phone: "",
      email: "ChandraSinaga@example.com",
      gender: "P",
      mapel: [],
      nip: "197906302010011017",
      type: "ASN",
      position: "",
      startDate: new Date("2024-08-07"),
      role: "TEACHER",
    }
  ];
  



const dataCourse = [
  {
    name: "Pendidikan Agama dan Budi Pekerti",
    code: "XAGAMA",
    grade: "X",
  },
  {
    name: "Pendidikan Agama dan Budi Pekerti",
    code: "XIAGAMA",
    grade: "XI",
  },
  {
    name: "Pendidikan Agama dan Budi Pekerti",
    code: "XIIAGAMA",
    grade: "XII",
  },
  {
    name: "Pendidikan Pancasila",
    code: "XPKN",
    grade: "X",
  },
  {
    name: "Pendidikan Pancasila",
    code: "XIPKN",
    grade: "XI",
  },
  {
    name: "Pendidikan Pancasila",
    code: "XIIPKN",
    grade: "XII",
  },
  {
    name: "Bahasa Indonesia",
    code: "XB.INDO",
    grade: "X",
  },
  {
    name: "Bahasa Indonesia",
    code: "XIB.INDO",
    grade: "XI",
  },
  {
    name: "Bahasa Indonesia",
    code: "XIIB.INDO",
    grade: "XII",
  },
  {
    name: "Pendidikan Jasmani, Olah Raga Dan Kesehatan",
    code: "XPJOK",
    grade: "X",
  },
  {
    name: "Pendidikan Jasmani, Olah Raga Dan Kesehatan",
    code: "XIPJOK",
    grade: "XI",
  },
  {
    name: "Sejarah",
    code: "XSEJARAH",
    grade: "X",
  },
  {
    name: "Sejarah",
    code: "XISEJARAH",
    grade: "XI",
  },
  {
    name: "Seni Budaya",
    code: "XSENI",
    grade: "X",
  },
  {
    name: "Mulok",
    code: "XMLK",
    grade: "X",
  },
  {
    name: "Mulok",
    code: "XIMLK",
    grade: "XI",
  },
  {
    name: "Matematika",
    code: "XMAT",
    grade: "X",
  },
  {
    name: "Matematika",
    code: "XIMAT",
    grade: "XI",
  },
  {
    name: "Matematika",
    code: "XIIMAT",
    grade: "XII",
  },
  {
    name: "Bahasa Inggris",
    code: "XB.ING",
    grade: "X",
  },
  {
    name: "Bahasa Inggris",
    code: "XIB.ING",
    grade: "XI",
  },
  {
    name: "Bahasa Inggris",
    code: "XIIB.ING",
    grade: "XII",
  },
  {
    name: "Informatika",
    code: "XINFOR",
    grade: "X",
  },
  {
    name: "Projek Ilmu Pengetahuan Alam dan Sosial",
    code: "XPIPAS",
    grade: "X",
  },
  {
    name: "Dasar Dasar Teknik Ketenagalistrikan",
    code: "XDTL",
    grade: "X",
  },
  {
    name: "Dasar Pengembangan Perangkat Lunak dan GIM",
    code: "XDPPLG",
    grade: "X",
  },
  {
    name: "Dasar Dasar Teknik Jaringan dan Telekomunikasi",
    code: "XDTJT",
    grade: "X",
  },
  {
    name: "Instalasi Penerangan Listrik",
    code: "XIIPL",
    grade: "XI",
  },
  {
    name: "Instalasi Penerangan Listrik",
    code: "XIIIPL",
    grade: "XII",
  },
  {
    name: "Instalasi Tenaga Listrik",
    code: "XIITL",
    grade: "XI",
  },
  {
    name: "Instalasi Tenaga Listrik",
    code: "XIIITL",
    grade: "XII",
  },
  {
    name: "Instalasi Motor Listrik",
    code: "XIIML",
    grade: "XI",
  },
  {
    name: "Instalasi Motor Listrik",
    code: "XIIIML",
    grade: "XII",
  },
  {
    name: "Perbaikan Peralatan Listrik",
    code: "XIIPPLis",
    grade: "XII",
  },
  {
    name: "Mapel Pilihan TITL: Elektronika",
    code: "XIMTITL",
    grade: "XI",
  },
  {
    name: "Produk Kreatif dan KWS",
    code: "XIKWS",
    grade: "XI",
  },
  {
    name: "Produk Kreatif dan KWS",
    code: "XIIKWS",
    grade: "XII",
  },
  {
    name: "Basis Data",
    code: "XIBD",
    grade: "XI",
  },
  {
    name: "Basis Data",
    code: "XIIBD",
    grade: "XII",
  },
  {
    name: "Pemrograman Berbasis Teks, Grafis, dan Multimedia",
    code: "XIPBTGM",
    grade: "XI",
  },
  {
    name: "Pemrograman WEB",
    code: "XIPW",
    grade: "XI",
  },
  {
    name: "Pemrograman Perangkat Bergerak",
    code: "XIPPB",
    grade: "XI",
  },
  {
    name: "Mapel Pilihan RPL: Menginstal Software",
    code: "XIMRPL",
    grade: "XI",
  },
  {
    name: "Pemrograman Berbasis Objek",
    code: "XIIPBO",
    grade: "XII",
  },
  {
    name: "Pemrograman Perangkat Bergerak",
    code: "XIIPPB",
    grade: "XII",
  },
  {
    name: "Pemrograman Web Perangkat Bergerak",
    code: "XIIPWPB",
    grade: "XII",
  },
  {
    name: "Perencanaan dan Pengalamatan Jaringan",
    code: "XIPPJ",
    grade: "XI",
  },
  {
    name: "Teknologi Jaringan Kabel dan Nirkabel",
    code: "XITJKN",
    grade: "XI",
  },
  {
    name: "Keamanan Jaringan",
    code: "XIKJ",
    grade: "XI",
  },
  {
    name: "Pemasangan dan Konfigurasi Perangkat Jaringan",
    code: "XIPKPJP",
    grade: "XI",
  },
  {
    name: "Administrasi Sistem Jaringan",
    code: "XIASJ",
    grade: "XI",
  },
  {
    name: "Administrasi Sistem Jaringan",
    code: "XIIASJ",
    grade: "XII",
  },
  {
    name: "Administrasi Infrastruktur Jaringan",
    code: "XIIAIJ",
    grade: "XII",
  },
  {
    name: "Teknologi Layanan Jaringan",
    code: "XIITLJ",
    grade: "XII",
  },
  {
    name: "Mapel Pilihan TKJ: Teknik Dasar Perbaikan Komputer",
    code: "XIMTKJ",
    grade: "XI",
  },
];

module.exports = {
  dataConfigSchool,
  customStudents,
  dataMajor,
  dataStaff,
  dataDeveloper,
  dataCourse,
};
