const dataConfigSchool = {
  name: "SMK NEGERI 1 LUMBAN JULU",
  historySchool:
    "SMK Negeri 1 Lumban Julu adalah institusi pendidikan kejuruan yang berfokus pada pengembangan keterampilan siswa di bidang teknologi, bisnis, dan layanan masyarakat. Kami berdedikasi untuk mencetak lulusan yang siap bersaing di dunia kerja maupun melanjutkan pendidikan ke jenjang yang lebih tinggi.",
  about:
    "SMK Negeri 1 Lumban Julu adalah institusi pendidikan kejuruan yang berfokus pada pengembangan keterampilan siswa di bidang teknologi, bisnis, dan layanan masyarakat. Kami berdedikasi untuk mencetak lulusan yang siap bersaing di dunia kerja maupun melanjutkan pendidikan ke jenjang yang lebih tinggi.",
  vision:
    "Menjadi sekolah kejuruan unggulan yang menghasilkan lulusan berkualitas, berkarakter, dan berkompeten di bidangnya untuk bersaing di era global.",
  mission:
    "1. Menyediakan pendidikan kejuruan yang berbasis teknologi dan kewirausahaan.\n2. Meningkatkan kompetensi siswa melalui pelatihan praktik kerja industri.\n3. Membentuk karakter siswa yang jujur, disiplin, dan bertanggung jawab.\n4. Mengembangkan kurikulum yang relevan dengan kebutuhan dunia kerja.\n5. Menjalin kemitraan dengan dunia usaha dan industri.",
  address: "Jalan Lintas Sumatera, Aeknatolu Jaya, Kecamatan Lumban Julu",
  telp: "+62 822-8302-0850",
  email: "info@smkn1lumbanjulu.sch.id",
  maps: '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15942.833059396076!2d99.0161061!3d2.6008913!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3031f01ad5a61e53%3A0xa1341928e9376e81!2sSMK%20Negeri%201%20Lumbanjulu!5e0!3m2!1sid!2sid!4v1731691727941!5m2!1sid!2sid" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
  npsn: "12345678",
  fb: "https://facebook.com/smkn1lumbanjulu",
  ig: "https://instagram.com/smkn1lumbanjulu",
  tiktok: "https://tiktok.com/@smkn1lumbanjulu",
};

// const customStudents = [
//   {
//     name: "Dhea Romantika",
//     nis: "223344",
//     nisn: "102938",
//     majorCode: "TKJ",
//     birthPlace: "Medan, 24 Februari 2003",
//     address: "Jl. Mawar No.1",
//     phone: "081234567890",
//     email: "dhea.romantika@example.com",
//     gender: "P",
//   },
//   {
//     name: "Rizky Fadillah",
//     nis: "112233",
//     nisn: "203948",
//     majorCode: "MM",
//     birthPlace: "Jakarta, 17 Desember 2002",
//     address: "Jl. Melati No.2",
//     phone: "081234567891",
//     email: "rizky.fadillah@example.com",
//     gender: "L",
//   },
//   {
//     name: "Muhammad Syahputra",
//     nis: "334455",
//     nisn: "304958",
//     majorCode: "RPL",
//     birthPlace: "Bandung, 22 April 2003",
//     address: "Jl. Kenanga No.3",
//     phone: "081234567892",
//     email: "muhammad.syahputra@example.com",
//     gender: "L",
//   },
// ];

const customStudents = [
  {
    name: "Alex Anggiat Halomoan Manurung",
    nis: "0091180224",
    nisn: "0091180224",
    majorCode: "TKJ",
    birthPlace: "Medan, 17 Oktober 2009",
    address: "Dusun V RT 0 / RW 0, Wonosari Kec. Tanjung Morawa Kab. Deli Serdang 20361",
    phone: "",
    email: "",
    gender: "L",
  },
  {
    name: "Charli Sirait",
    nis: "0095031363",
    nisn: "0095031363",
    majorCode: "TKJ",
    birthPlace: "Lumban Lintong, 13 Maret 2009",
    address: "Lumban Lintong RT 0 / RW 0, Lintongjulu Kec. Lumban Julu Prov. Sumatera Utara 22386",
    phone: "085270558275",
    email: "",
    gender: "L",
  },
  {
    name: "Eklesia Sinaga",
    nis: "0081230202",
    nisn: "0081230202",
    majorCode: "TKJ",
    birthPlace: "Palembang, 24 November 2008",
    address: "Bukit Betabuh RT 2 / RW 5, Pauhranap Kec. Peranap Prov. Riau29354",
    phone: "085215991530",
    email: "",
    gender: "L",
  },
  {
    name: "Friska Manik",
    nis: "0073936824",
    nisn: "0073936824",
    majorCode: "TKJ",
    birthPlace: "Panji Bako , 20 Desember 2007",
    address: "Jl. Dr Sutan Raja Dl Sitorus RT 0 / RW 0, Pardamean Kec. Ajibata Kab. Toba 21174",
    phone: "082213964107",
    email: "",
    gender: "P",
  },
  {
    name: "Gebi Stevani Sihombing",
    nis: "0096236210",
    nisn: "0096236210",
    majorCode: "TKJ",
    birthPlace: "Narumontak, 18 September 2009",
    address: "Narumontak RT 0 / RW 0, Patane Ii Kec. Porsea Kab. Toba 22384",
    phone: "088807249694",
    email: "",
    gender: "P",
  },
  {
    name: "Gospel Paul Sinaga",
    nis: "0083564800",
    nisn: "0083564800",
    majorCode: "TKJ",
    birthPlace: "Girsang, 21 Oktober 2008",
    address: "Jl.anggarajim RT 0 / RW 0, Girsang Kec. Girsang Simpangan Bolon Kab. Simalungun 21174",
    phone: "",
    email: "",
    gender: "L",
  },
  {
    name: "Ira Naomi Marsanda Aritonang",
    nis: "0094305425",
    nisn: "0094305425",
    majorCode: "TKJ",
    birthPlace: "Pekanbaru, 20 Juli 2009",
    address: "Dsn Iv Plambayan RT 36 / RW 9, Desa Kota Garo Kec. Tapung Hilir Prov. Riau 28464",
    phone: "085374557982",
    email: "",
    gender: "P",
  },
  {
    name: "Johannes Nathaniel Julius",
    nis: "0089067461",
    nisn: "0089067461",
    majorCode: "TKJ",
    birthPlace: "Tangerang, 20 November 2008",
    address: "Aek Natolu Jaya RT 0 / RW 0, Aek Natolu Jaya Kec. Lumban Julu Kab. Toba 22386",
    phone: "",
    email: "",
    gender: "L",
  },
  {
    name: "Johannes Tamba",
    nis: "0092197925",
    nisn: "0092197925",
    majorCode: "TKJ",
    birthPlace: "Pematang Siantar, 29 Januari 2010",
    address: "Jl Sumatera Utara RT 0 / RW 0, Aeknatolu Jaya Kec. Lumban Julu Prov. Sumatera Utara 22386",
    phone: "",
    email: "",
    gender: "L",
  },
  {
    name: "Josua Manurung",
    nis: "0109804056",
    nisn: "0109804056",
    majorCode: "TKJ",
    birthPlace: "Sosor Lintong, 07 Maret 2010",
    address: "Lumban Hailhail RT 0 / RW 0, Sibaruang Kec. Lumban Julu Kab. Toba 22386",
    phone: "",
    email: "",
    gender: "L",
  },
];

const dataMajor = [
  {
    name: "Teknik Komputer dan Jaringan",
    majorCode: "TKJ",
    description:
      "Jurusan yang berfokus pada teknologi komputer, jaringan, dan sistem keamanan data. Siswa akan mempelajari perakitan komputer, instalasi sistem operasi, administrasi server, serta konfigurasi jaringan lokal (LAN) dan internet.",
  },
  {
    name: "Multimedia ",
    majorCode: "MM",
    description:
      "Jurusan yang mengajarkan keterampilan dalam desain grafis, animasi, videografi, dan pengembangan media digital. Siswa akan mempelajari software desain, editing video, pembuatan konten kreatif, serta produksi media interaktif.",
  },
  {
    name: "Rekayasa Perangkat Lunak",
    majorCode: "RPL",
    description:
      "Jurusan yang berfokus pada pengembangan perangkat lunak, termasuk pemrograman, analisis sistem, dan manajemen basis data. Siswa akan belajar membuat aplikasi berbasis web, mobile, dan desktop menggunakan berbagai bahasa pemrograman.",
  },
  {
    name: "Teknik Instalasi Tenaga Listrik",
    majorCode: "TITL",
    description:
      "Jurusan yang mengajarkan tentang instalasi, perawatan, dan perbaikan sistem kelistrikan. Siswa akan mempelajari sistem tenaga listrik, instalasi rumah dan industri, serta perancangan dan perawatan jaringan listrik.",
  },
];

const dataDeveloper = {
  name: "developer",
  birthPlace: "21 Juni 1961",
  address: "Solo",
  phone: "08536746398",
  email: "developer@gmail.com",
  gender: "L",
  mapel: [],
  nip: "P001",
  type: "PH",
  position: "",
  startDate: new Date("2024-08-07"),
  role: "STAFF",
};

const dataStaff = [
  {
    name: "Drs Mutiha Hutajulu, M. Pd",
    birthPlace: "Tempat, 02 Maret 1966",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "196603021990031008",
    type: "ASN",
    position: "Kepala Sekolah",
    startDate: new Date("1990-03-01"),
    role: "TEACHER",
  },
  {
    name: "Adra Manurung, S. Pd, M. Si",
    birthPlace: "Tempat, 21 Oktober 1964",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "196410211988031001",
    type: "ASN",
    position: "Kepala Laboratorium",
    startDate: new Date("1988-03-01"),
    role: "TEACHER",
  },
  {
    name: "Rosira Manurung, S. Pd",
    birthPlace: "Tempat, 07 Februari 1965",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "196502071988032004",
    type: "ASN",
    position: "",
    startDate: new Date("1988-03-01"),
    role: "TEACHER",
  },
  {
    name: "Dra. Ul M Tambunan",
    birthPlace: "Tempat, 16 November 1967",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "196711162008022001",
    type: "ASN",
    position: "Ka.Perpustakaan + Wali Kelas XI TITL",
    startDate: new Date("2008-02-01"),
    role: "TEACHER",
  },
  {
    name: "Noveltna Simanjumak, S. Pd",
    birthPlace: "Tempat, 18 November 1983",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "198311182008042001",
    type: "ASN",
    position: "Wa.Kurikulum",
    startDate: new Date("2008-04-01"),
    role: "TEACHER",
  },
  {
    name: "Natalina Simaremare, S. Pd",
    birthPlace: "Tempat, 25 Desember 1981",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "198112252009032005",
    type: "ASN",
    position: "Wa.Kesiswaan",
    startDate: new Date("2009-03-01"),
    role: "TEACHER",
  },
  {
    name: "Santoso Sinaga, S. Th",
    birthPlace: "Tempat, 14 Juni 1982",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "198206142009031001",
    type: "ASN",
    position: "Wali Kelas XI TKJ 2",
    startDate: new Date("2009-03-01"),
    role: "TEACHER",
  },
  {
    name: "Rosi Ara Sirait, S. Pd",
    birthPlace: "Tempat, 20 Desember 1983",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "198312202009032002",
    type: "ASN",
    position: "",
    startDate: new Date("2009-03-01"),
    role: "TEACHER",
  },
  {
    name: "Julian Situmorang, S. Pd",
    birthPlace: "Tempat, 14 Juli 1984",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "198407142009031003",
    type: "ASN",
    position: "Wa.Sarana dan Prasarana",
    startDate: new Date("2009-03-01"),
    role: "TEACHER",
  },
  {
    name: "Frans R Situmcang, S. Pd",
    birthPlace: "Tempat, 16 Februari 1980",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "198002162009031002",
    type: "ASN",
    position: "",
    startDate: new Date("2009-03-01"),
    role: "TEACHER",
  },
  {
    name: "Pirman E Sinaga, S. Kom",
    birthPlace: "Tempat, 04 Januari 1983",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "198301042010011016",
    type: "ASN",
    position: "Bendahara BOS + Kapro TITL",
    startDate: new Date("2010-01-01"),
    role: "TEACHER",
  },
  {
    name: "Roma Silorus, S. Pd",
    birthPlace: "Tempat, 06 September 1982",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "198209062009032002",
    type: "ASN",
    position: "",
    startDate: new Date("2009-03-01"),
    role: "TEACHER",
  },
  {
    name: "April Sirait, S. Kom",
    birthPlace: "Tempat, 12 April 1982",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "198204122010011034",
    type: "ASN",
    position: "",
    startDate: new Date("2010-01-01"),
    role: "TEACHER",
  },
  {
    name: "Naek Sirait, S. Si",
    birthPlace: "Tempat, 29 Februari 1981",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "198102292011041001",
    type: "ASN",
    position: "Wali Kelas XI TKJ 2",
    startDate: new Date("2011-04-01"),
    role: "TEACHER",
  },
  {
    name: "Vivi Septiantia Huabanat, S. Kom",
    birthPlace: "Tempat, 30 September 1986",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "198609302015052001",
    type: "ASN",
    position: "Wali Kelas XI TKJ 1",
    startDate: new Date("2015-05-01"),
    role: "TEACHER",
  },
  {
    name: "Lenny R Butarbutur, S. Pd",
    birthPlace: "Tempat, 03 Mei 1976",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "197605032014082001",
    type: "ASN",
    position: "Pelugas Perpustakaan",
    startDate: new Date("2014-08-01"),
    role: "TEACHER",
  },
  {
    name: "Stituurbaya Pulungan, S. Pdi",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "1",
    type: "P3K",
    position: "Wali Kelas XII TITL",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Tangrija Butarbutur, S. Ag",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "2",
    type: "P3K",
    position: "Wali Kelas XII TITL",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Hendra F Manurung, S. Kom",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "3",
    type: "P3K",
    position: "Wali Kelas XII RPL 2",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Richo S Manurung, S. Kom",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "4",
    type: "P3K",
    position: "",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Tunggul B Sirait, S. Kom",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "5",
    type: "GTT",
    position: "",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Marti Silombing, S. Pd",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "6",
    type: "GTT",
    position: "Koordinator BK + Wali Kelas XII RPL1",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Rusmini Simaremare, S. Kom",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "7",
    type: "GTT",
    position: "Kapro RPL + Wali Kelas XI RPL1",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Aprira U Manurung, S. Pd",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "8",
    type: "GTT",
    position: "Wali Kelas XI RPL2",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Pince Sitorus, S. Th",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "9",
    type: "GTT",
    position: "Wali Kelas XI TITL",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Desy A Simanjuraki, S. Pd",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "10",
    type: "GH",
    position: "Wali Kelas XI TKJ 1",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Christy Manurung, M. Pd",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "11",
    type: "GH",
    position: "Pembina OSIS",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Risalina Shilahi, S.Pd",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "12",
    type: "GH",
    position: "Wali Kelas X TKJ 2",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Josua Manurung, S. Pd",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "13",
    type: "GH",
    position: "Wali Kelas X RPL 1 + Pembina OSIS",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Sindi Maria Santuri S. Kom",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "14",
    type: "GH",
    position: "",
    startDate: new Date("2024-08-07"),
    role: "TEACHER",
  },
  {
    name: "Chandra K Sinaga, Amd",
    birthPlace: "Tempat, 30 Juni 1979",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "197906302010011017",
    type: "ASN",
    position: "Kepala TU",
    startDate: new Date("2010-01-01"),
    role: "STAFF",
  },
  {
    name: "Tony H Manurung",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "15",
    type: "PH",
    position: "TU Bidang Kurikulum",
    startDate: new Date("2024-08-07"),
    role: "STAFF",
  },
  {
    name: "Nurmaila Sirait",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "16",
    type: "PH",
    position: "TU Bidang Kesiswaan",
    startDate: new Date("2024-08-07"),
    role: "STAFF",
  },
  {
    name: "Ria Anjerima A.md Keb",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "17",
    type: "PH",
    position: "Tenaga Kesehatan",
    startDate: new Date("2024-08-07"),
    role: "STAFF",
  },
  {
    name: "Christian Simarat",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "P",
    mapel: [],
    nip: "18",
    type: "PH",
    position: "TU Kurikulum",
    startDate: new Date("2024-08-07"),
    role: "STAFF",
  },
  {
    name: "Liber Fernando Manik",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "19",
    type: "PH",
    position: "TU Sarana Prasarana",
    startDate: new Date("2024-08-07"),
    role: "STAFF",
  },
  {
    name: "Justoro Pasaribu",
    birthPlace: "Tempat, ",
    address: "",
    phone: "",
    email: "",
    gender: "L",
    mapel: [],
    nip: "20",
    type: "PH",
    position: "Penjaga Sekolah",
    startDate: new Date("2024-08-07"),
    role: "STAFF",
  },
];

const dataCourse = [
  {
    name: "Pendidikan Agama dan Budi Pekerti",
    code: "XAGAMA",
    grade: "X",
  },
  {
    name: "Pendidikan Agama dan Budi Pekerti",
    code: "XIAGAMA",
    grade: "XI",
  },
  {
    name: "Pendidikan Agama dan Budi Pekerti",
    code: "XIIAGAMA",
    grade: "XII",
  },
  {
    name: "Pendidikan Pancasila",
    code: "XPKN",
    grade: "X",
  },
  {
    name: "Pendidikan Pancasila",
    code: "XIPKN",
    grade: "XI",
  },
  {
    name: "Pendidikan Pancasila",
    code: "XIIPKN",
    grade: "XII",
  },
  {
    name: "Bahasa Indonesia",
    code: "XB.INDO",
    grade: "X",
  },
  {
    name: "Bahasa Indonesia",
    code: "XIB.INDO",
    grade: "XI",
  },
  {
    name: "Bahasa Indonesia",
    code: "XIIB.INDO",
    grade: "XII",
  },
  {
    name: "Pendidikan Jasmani, Olah Raga Dan Kesehatan",
    code: "XPJOK",
    grade: "X",
  },
  {
    name: "Pendidikan Jasmani, Olah Raga Dan Kesehatan",
    code: "XIPJOK",
    grade: "XI",
  },
  {
    name: "Sejarah",
    code: "XSEJARAH",
    grade: "X",
  },
  {
    name: "Sejarah",
    code: "XISEJARAH",
    grade: "XI",
  },
  {
    name: "Seni Budaya",
    code: "XSENI",
    grade: "X",
  },
  {
    name: "Mulok",
    code: "XMLK",
    grade: "X",
  },
  {
    name: "Mulok",
    code: "XIMLK",
    grade: "XI",
  },
  {
    name: "Matematika",
    code: "XMAT",
    grade: "X",
  },
  {
    name: "Matematika",
    code: "XIMAT",
    grade: "XI",
  },
  {
    name: "Matematika",
    code: "XIIMAT",
    grade: "XII",
  },
  {
    name: "Bahasa Inggris",
    code: "XB.ING",
    grade: "X",
  },
  {
    name: "Bahasa Inggris",
    code: "XIB.ING",
    grade: "XI",
  },
  {
    name: "Bahasa Inggris",
    code: "XIIB.ING",
    grade: "XII",
  },
  {
    name: "Informatika",
    code: "XINFOR",
    grade: "X",
  },
  {
    name: "Projek Ilmu Pengetahuan Alam dan Sosial",
    code: "XPIPAS",
    grade: "X",
  },
  {
    name: "Dasar Dasar Teknik Ketenagalistrikan",
    code: "XDTL",
    grade: "X",
  },
  {
    name: "Dasar Pengembangan Perangkat Lunak dan GIM",
    code: "XDPPLG",
    grade: "X",
  },
  {
    name: "Dasar Dasar Teknik Jaringan dan Telekomunikasi",
    code: "XDTJT",
    grade: "X",
  },
  {
    name: "Instalasi Penerangan Listrik",
    code: "XIIPL",
    grade: "XI",
  },
  {
    name: "Instalasi Penerangan Listrik",
    code: "XIIIPL",
    grade: "XII",
  },
  {
    name: "Instalasi Tenaga Listrik",
    code: "XIITL",
    grade: "XI",
  },
  {
    name: "Instalasi Tenaga Listrik",
    code: "XIIITL",
    grade: "XII",
  },
  {
    name: "Instalasi Motor Listrik",
    code: "XIIML",
    grade: "XI",
  },
  {
    name: "Instalasi Motor Listrik",
    code: "XIIIML",
    grade: "XII",
  },
  {
    name: "Perbaikan Peralatan Listrik",
    code: "XIIPPLis",
    grade: "XII",
  },
  {
    name: "Mapel Pilihan TITL: Elektronika",
    code: "XIMTITL",
    grade: "XI",
  },
  {
    name: "Produk Kreatif dan KWS",
    code: "XIKWS",
    grade: "XI",
  },
  {
    name: "Produk Kreatif dan KWS",
    code: "XIIKWS",
    grade: "XII",
  },
  {
    name: "Basis Data",
    code: "XIBD",
    grade: "XI",
  },
  {
    name: "Basis Data",
    code: "XIIBD",
    grade: "XII",
  },
  {
    name: "Pemrograman Berbasis Teks, Grafis, dan Multimedia",
    code: "XIPBTGM",
    grade: "XI",
  },
  {
    name: "Pemrograman WEB",
    code: "XIPW",
    grade: "XI",
  },
  {
    name: "Pemrograman Perangkat Bergerak",
    code: "XIPPB",
    grade: "XI",
  },
  {
    name: "Mapel Pilihan RPL: Menginstal Software",
    code: "XIMRPL",
    grade: "XI",
  },
  {
    name: "Pemrograman Berbasis Objek",
    code: "XIIPBO",
    grade: "XII",
  },
  {
    name: "Pemrograman Perangkat Bergerak",
    code: "XIIPPB",
    grade: "XII",
  },
  {
    name: "Pemrograman Web Perangkat Bergerak",
    code: "XIIPWPB",
    grade: "XII",
  },
  {
    name: "Perencanaan dan Pengalamatan Jaringan",
    code: "XIPPJ",
    grade: "XI",
  },
  {
    name: "Teknologi Jaringan Kabel dan Nirkabel",
    code: "XITJKN",
    grade: "XI",
  },
  {
    name: "Keamanan Jaringan",
    code: "XIKJ",
    grade: "XI",
  },
  {
    name: "Pemasangan dan Konfigurasi Perangkat Jaringan",
    code: "XIPKPJP",
    grade: "XI",
  },
  {
    name: "Administrasi Sistem Jaringan",
    code: "XIASJ",
    grade: "XI",
  },
  {
    name: "Administrasi Sistem Jaringan",
    code: "XIIASJ",
    grade: "XII",
  },
  {
    name: "Administrasi Infrastruktur Jaringan",
    code: "XIIAIJ",
    grade: "XII",
  },
  {
    name: "Teknologi Layanan Jaringan",
    code: "XIITLJ",
    grade: "XII",
  },
  {
    name: "Mapel Pilihan TKJ: Teknik Dasar Perbaikan Komputer",
    code: "XIMTKJ",
    grade: "XI",
  },
];

module.exports = {
  dataConfigSchool,
  customStudents,
  dataMajor,
  dataStaff,
  dataDeveloper,
  dataCourse,
};
